# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 14:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flurryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadriver',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
