# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flurryapp', '0003_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driving_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='flurryapp.DataDriver'),
        ),
    ]
